program Inventory;

uses
  Forms,
  MAIN in 'MAIN.pas' {frmMenu},
  ufrmCxBrowse in 'ufrmCxBrowse.pas' {frmCxBrowse},
  UfrmLogin in 'UfrmLogin.pas' {frmLogin},
  ufrmUser in 'ufrmUser.pas' {frmUser},
  uFrmbantuan in 'bantu\uFrmbantuan.pas' {frmBantuan},
  Ulib in 'bantu\Ulib.pas',
  uModuleConnection in 'bantu\uModuleConnection.pas',
  uReport in 'bantu\uReport.pas',
  ufrmBrowseGudang in 'ufrmBrowseGudang.pas' {frmBrowseGudang},
  ufrmGudang in 'ufrmGudang.pas' {frmGudang},
  ufrmBrowseCostCenter in 'ufrmBrowseCostCenter.pas' {frmBrowseCostCenter},
  ufrmCostCenter in 'ufrmCostCenter.pas' {frmCostCenter},
  ufrmBrowseSalesman in 'ufrmBrowseSalesman.pas' {frmBrowseSalesman},
  ufrmSalesman in 'ufrmSalesman.pas' {frmSalesman},
  ufrmBrowseCustomer in 'ufrmBrowseCustomer.pas' {frmBrowseCustomer},
  ufrmCustomer in 'ufrmCustomer.pas' {frmCustomer},
  ufrmBrowseSupplier in 'ufrmBrowseSupplier.pas' {frmBrowseSupplier},
  ufrmSupplier in 'ufrmSupplier.pas' {frmSupplier},
  ufrmBrowseJC in 'ufrmBrowseJC.pas' {frmBrowseJC},
  ufrmJC in 'ufrmJC.pas' {frmJC},
  ufrmBrowseSubBarang in 'ufrmBrowseSubBarang.pas' {frmBrowseSubBarang},
  ufrmSubBarang in 'ufrmSubBarang.pas' {frmSubBarang},
  ufrmPesanan in 'ufrmPesanan.pas' {frmPesanan},
  ufrmBrowseBarang in 'ufrmBrowseBarang.pas' {frmBrowseBarang},
  ufrmBarang in 'ufrmBarang.pas' {frmBarang},
  ufrmBrowsePesanan in 'ufrmBrowsePesanan.pas' {frmBrowsePesanan},
  ufrmBrowsePO in 'ufrmBrowsePO.pas' {frmBrowsePO},
  ufrmPO in 'ufrmPO.pas' {frmPO},
  ufrmBrowseBPB in 'ufrmBrowseBPB.pas' {frmBrowseBPB},
  ufrmBPB in 'ufrmBPB.pas' {frmBPB},
  ufrmInvoice in 'ufrmInvoice.pas' {frmInvoice},
  ufrmBrowseInvoice in 'ufrmBrowseInvoice.pas' {frmBrowseInvoice},
  ufrmBrowseMutasiGudang in 'ufrmBrowseMutasiGudang.pas' {frmBrowseMutasiGudang},
  ufrmMutasiGudang in 'ufrmMutasiGudang.pas' {frmMutasiGudang},
  ufrmBayarSupplier in 'ufrmBayarSupplier.pas' {frmBayarSupplier},
  ufrmBrowseMutasiCabang in 'ufrmBrowseMutasiCabang.pas' {frmBrowseMutasiCabang},
  ufrmMutasiCabang in 'ufrmMutasiCabang.pas' {frmMutasiCabang},
  ufrmBrowseReturBeli in 'ufrmBrowseReturBeli.pas' {frmBrowseReturBeli},
  ufrmReturBeli in 'ufrmReturBeli.pas' {frmReturBeli},
  ufrmBrowseRekening in 'ufrmBrowseRekening.pas' {frmBrowseRekening},
  ufrmRekening in 'ufrmRekening.pas' {frmRekening},
  ufrmBrowsePenerimaanLain in 'ufrmBrowsePenerimaanLain.pas' {frmBrowsePenerimaanLain},
  ufrmPenerimaanLain in 'ufrmPenerimaanLain.pas' {frmPenerimaanLain},
  ufrmPembayaranLain in 'ufrmPembayaranLain.pas' {frmPembayaranLain},
  ufrmBrowsePembayaranLain in 'ufrmBrowsePembayaranLain.pas' {frmBrowsePembayaranLain},
  ufrmBrowseHitungStok in 'ufrmBrowseHitungStok.pas' {frmBrowseHitungStok},
  ufrmHitungStok in 'ufrmHitungStok.pas' {frmHitungStok},
  ufrmBrowseBayarSupplier in 'ufrmBrowseBayarSupplier.pas' {frmBrowseBayarSupplier},
  ufrmBrowseJurnalUmum in 'ufrmBrowseJurnalUmum.pas' {frmBrowseJurnalUmum},
  ufrmJurnalUmum in 'ufrmJurnalUmum.pas' {frmJurnalUmum},
  ufrmListKas in 'ufrmListKas.pas' {frmListKas},
  ufrmPerusahaan in 'ufrmPerusahaan.pas' {frmPerusahaan},
  ufrmBrowseJurnal in 'ufrmBrowseJurnal.pas' {frmBrowseJurnal},
  ufrmListIOS in 'ufrmListIOS.pas' {frmListIOS},
  ufrmProsesAmbilJurnal in 'ufrmProsesAmbilJurnal.pas' {frmProsesAmbilJurnal},
  ufrmListSaldoHutang in 'ufrmListSaldoHutang.pas' {frmListSaldohutang},
  ufrmKoreksiStok in 'ufrmKoreksiStok.pas' {frmKoreksiStok},
  ufrmBrowseKoreksiStok in 'ufrmBrowseKoreksiStok.pas' {frmBrowseKoreksiStok},
  ufrmListMutasiStok2 in 'ufrmListMutasiStok2.pas' {frmListMutasiStok2},
  ufrmBrowseMutasiCabang2 in 'ufrmBrowseMutasiCabang2.pas' {frmBrowseMutasiCabang2},
  ufrmMutasiCabang2 in 'ufrmMutasiCabang2.pas' {frmMutasiCabang2},
  ufrmListTransaksiHarian2 in 'ufrmListTransaksiHarian2.pas' {frmListTransaksiHarian2},
  ufrmProsesGaji in 'ufrmProsesGaji.pas' {frmProsesGaji},
  ufrmtutupperiode in 'ufrmTutupPeriode.pas' {frmTutupPeriode},
  ufrmCekKasBank in 'ufrmCekKasBank.pas' {frmCekKasBank},
  ufrmNeracaSaldo in 'ufrmNeracaSaldo.pas' {frmNeracaSaldo},
  ufrmCekTransaksiKasBank in 'ufrmCekTransaksiKasBank.pas' {frmCekTransaksiKasBank},
  ufrmLapRekapPermintaanBarang in 'ufrmLapRekapPermintaanBarang.pas' {frmLapRekapPermintaanBarang},
  ufrmBrowseJurnal2 in 'ufrmBrowsejurnal2.pas' {frmBrowseJurnal2},
  ufrmPostingJurnalBulanan in 'ufrmPostingJurnalBulanan.pas' {frmPostingJurnalBulanan},
  ufrmLapBiayaBulanan in 'ufrmLapBiayaBulanan.pas' {frmLapBiayaBulanan},
  ufrmBrowseKartuStok in 'ufrmBrowseKartuStok.pas' {frmBrowseKartuStok},
  UfrmOtorisasi in 'UfrmOtorisasi.pas' {frmOtorisasi},
  ufrmCekMutasiBarang in 'ufrmCekMutasiBarang.pas' {frmCekMutasiBarang},
  ufrmLapLabaRugi in 'ufrmLapLabaRugi.pas' {frmLapLabaRugi},
  ufrmLapNeraca in 'ufrmLapNeraca.pas' {frmLapNeraca},
  ufrmLapAnggaran in 'ufrmLapAnggaran.pas' {frmLapAnggaran},
  ufrmLaporanChekin in 'ufrmLaporanChekin.pas' {frmLaporanChekin},
  uFrmbantuan2 in 'bantu\uFrmbantuan2.pas' {frmBantuan2},
  ufrmBrowseHargaBeliNew in 'ufrmBrowseHargaBeliNew.pas' {frmBrowseHargaBeliNew},
  ufrmSettingHet in 'ufrmSettingHet.pas' {frmSettingHet},
  ufrmSubBarangPF in 'ufrmSubBarangPF.pas' {frmSubBarangPF},
  ufrmBrowseSubBarangPF in 'ufrmBrowseSubBarangPF.pas' {frmBrowseSubBarangPF},
  ufrmBrowseSetingbarangpf in 'ufrmBrowseSetingbarangpf.pas' {frmBrowseSetingBarangPF},
  ufrmSetingBarangPF in 'ufrmSetingBarangPF.pas' {frmSetingBarangPF},
  ufrmLapAllPf in 'ufrmLapAllpf.pas' {frmLapAllPf},
  ufrmLapAllpf2 in 'ufrmLapAllpf2.pas' {frmLapAllPf2},
  ufrmLaplabarugi2 in 'ufrmLaplabarugi2.pas' {frmLapLabaRugi2},
  ufrmListJual in 'ufrmListJual.pas' {frmListJual},
  ufrmAmbildataPenjualan in 'ufrmAmbildataPenjualan.pas' {frmAmbilDataPenjualan},
  ufrmKoreksiStok2 in 'ufrmKoreksiStok2.pas' {frmKoreksiStok2},
  ufrmListJualPFvsRiil in 'ufrmListJualPFvsRiil.pas' {frmListJualPFvsRiil},
  ufrmCreatePo in 'ufrmCreatePo.pas' {frmCreatePO},
  ufrmLapPersediaanAll in 'ufrmLapPersediaanAll.pas' {frmLapPersediaanAll},
  ufrmListPermintaanBarang in 'ufrmListPermintaanBarang.pas' {frmListPermintaanBarang},
  ufrmListFOS in 'ufrmListFOS.pas' {frmListFOS},
  ufrmBrowseKaryawanAll in 'ufrmBrowseKaryawanAll.pas' {frmBrowseKaryawanAll},
  ufrmVerifikasiAbsensi in 'ufrmVerifikasiAbsensi.pas' {frmVerifikasiAbsensi},
  ufrmBrowseBayarRepack in 'ufrmBrowseBayarRepack.pas' {frmBrowseBayarRepack},
  ufrmBayarRepack in 'ufrmBayarRepack.pas' {frmBayarRepack};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TfrmMenu, frmMenu);
  Application.CreateForm(TfrmLogin, frmLogin);
  Application.CreateForm(TfrmBantuan2, frmBantuan2);
  Application.Run;
 end.
